export interface Artwork {
  id: string;
  title: string;
  file: string;
  year: number;
  medium: string;
  dimensions?: string;
  price?: number;
  status: 'available' | 'sold' | 'nfs';
  description: string;
  longDescription: string;
  tags: string[];
  colors: string[];
  influences: string[];
  techniques: string[];
  mood: string[];
  seoTitle: string;
  seoDescription: string;
  altText: string;
  featured: boolean;
  order: number;
  printUrl?: string;
  printSizes?: string[];
}

export const artworks: Artwork[] = [
  {
    id: 'totem',
    title: 'Totem',
    file: '/art/totem.jpg',
    year: 2024,
    medium: 'Acrylic and spray paint on canvas',
    status: 'available',
    description: 'A teeming column of interlocking eyes, faces, and animal-like forms recalls indigenous carved poles reimagined through a street-art lens. Spray-painted atmospheric washes behind crisp graphic outlines create a charged dialogue between primal iconography and contemporary urban energy.',
    longDescription: 'Totem stacks a teeming column of interlocking eyes, faces, and animal-like forms into a vertical figure that recalls indigenous carved poles reimagined through a street-art lens. MacDonald layers spray-painted atmospheric washes behind crisp, graphic outlines, creating a charged dialogue between primal iconography and contemporary urban energy. Every eye watches. Every mouth speaks. The figure is both guardian and warning.',
    tags: ['totemic', 'faces', 'eyes', 'street art', 'vertical', 'figurative', 'stacked forms'],
    colors: ['#2E7EC7', '#A83B2A', '#D4A24C', '#1B7A5D', '#C86E9A'],
    influences: ['Jean-Michel Basquiat', 'Pacific Northwest totem poles', 'CoBrA movement', 'Pablo Picasso'],
    techniques: ['stenciling', 'spray paint layering', 'bold outlining', 'mixed media', 'gestural mark-making'],
    mood: ['vigilant', 'totemic', 'cacophonous', 'ancestral', 'hallucinatory'],
    seoTitle: 'Totem | Michael MacDonald | 137 Studio',
    seoDescription: 'Totem by Michael MacDonald — a mixed-media painting stacking eyes, faces & animal forms into a vivid urban-totemic column. Contemporary art for sale.',
    altText: 'Colorful vertical totem of stacked eyes, faces, and animal forms in blue, sienna, and gold by Michael MacDonald',
    featured: true,
    order: 1,
  },
  {
    id: 'composite-head',
    title: 'Composite Head',
    file: '/art/composite-head.jpg',
    year: 2024,
    medium: 'Acrylic, spray paint, and marker on canvas',
    status: 'available',
    description: 'Dozens of nested sub-faces, eyes, and mechanical appendages fracture a monumental portrait, each vying for dominance within a single cranium. The graffiti-dusted background and white painted border create a frame-within-a-frame tension.',
    longDescription: 'Composite Head fractures a monumental portrait into dozens of nested sub-faces, eyes, and mechanical appendages, each vying for dominance within a single cranium. The graffiti-dusted background and white painted border create a frame-within-a-frame tension, suggesting a specimen pinned between the gallery wall and the chaos of the subconscious. A Cubist archaeology of the self.',
    tags: ['portrait', 'cubist', 'faces', 'eyes', 'composite', 'fragmented', 'street art'],
    colors: ['#2B6FBF', '#9E3A24', '#D1A748', '#4CA895', '#C76FA0'],
    influences: ['Picasso', 'Arcimboldo', 'Jean Dubuffet', 'KAWS', 'George Condo'],
    techniques: ['heavy contour lines', 'spray paint misting', 'stencil patterning', 'cubist fragmentation', 'drip work'],
    mood: ['fragmented', 'cerebral', 'restless', 'confrontational', 'layered'],
    seoTitle: 'Composite Head | Michael MacDonald | 137 Studio',
    seoDescription: 'Composite Head by Michael MacDonald — a Cubist mixed-media portrait of interlocking faces and eyes on a graffiti-layered ground. Contemporary art.',
    altText: 'Cubist composite portrait with multiple nested faces and eyes in blue, rust, and amber by Michael MacDonald',
    featured: true,
    order: 2,
  },
  {
    id: 'math-chaos',
    title: 'Math Chaos',
    file: '/art/math-chaos.jpg',
    year: 2024,
    medium: 'Spray paint and acrylic on canvas',
    status: 'available',
    description: 'Strata of spray-painted numerals, physics equations, and a central tessellated triangle grid glow magenta through veils of red and purple. The piece collapses the language of mathematics into pure visual sensation.',
    longDescription: 'Math Chaos buries the viewer beneath strata of spray-painted numerals, physics equations, and a central tessellated triangle grid that glows magenta through veils of red and purple. The piece collapses the language of mathematics into pure visual sensation, suggesting that the universe\'s underlying order and its apparent chaos are one and the same. Numbers become texture. Equations become rhythm.',
    tags: ['mathematics', 'equations', 'geometry', 'numbers', 'sacred geometry', 'abstract', 'triangles'],
    colors: ['#D42B4E', '#C74BB5', '#2AAFBF', '#5E2D7A', '#1D9E7A'],
    influences: ['RETNA', 'Jasper Johns', 'Bridget Riley', 'Joseph Beuys', 'Mark Tobey'],
    techniques: ['spray paint stenciling', 'overlapping translucent layers', 'geometric tessellation', 'hand-painted equations', 'color-field gradients'],
    mood: ['frenetic', 'cerebral', 'electric', 'saturated', 'pulsing'],
    seoTitle: 'Math Chaos | Michael MacDonald | 137 Studio',
    seoDescription: 'Math Chaos by Michael MacDonald — vibrant mixed-media painting layering equations, numerals & sacred geometry in magenta, red & cyan. Art for sale.',
    altText: 'Dense layered painting of numbers, equations, and triangle grids in magenta, red, and cyan by Michael MacDonald',
    featured: true,
    order: 3,
  },
  {
    id: 'cruciform',
    title: 'Cruciform',
    file: '/art/cruciform.jpg',
    year: 2024,
    medium: 'Acrylic on canvas with combed texture',
    status: 'available',
    description: 'A smoldering field of crimson and maroon scored with sweeping combed arcs, its heavily worked surface evoking geological strata or ancient frescoes stripped back to plaster. A single stark white cross anchors the lower right.',
    longDescription: 'Cruciform presents a smoldering field of crimson and maroon scored with sweeping combed arcs, its heavily worked surface evoking geological strata or ancient frescoes stripped back to plaster. A single stark white cross anchors the lower right, its pristine geometry offering a moment of stillness against the surrounding turbulence. Devotional and wounded in equal measure.',
    tags: ['abstract', 'cross', 'textured', 'devotional', 'crimson', 'meditative'],
    colors: ['#7A2318', '#A83E2B', '#3D9E8B', '#4A2630', '#F0EDE4'],
    influences: ['Antoni Tapies', 'Anselm Kiefer', 'Gerhard Richter', 'Alberto Burri', 'Byzantine iconography'],
    techniques: ['combed texture', 'heavy impasto', 'sgraffito', 'transparent glazing', 'subtractive removal'],
    mood: ['solemn', 'brooding', 'excavated', 'devotional', 'meditative', 'wounded'],
    seoTitle: 'Cruciform | Michael MacDonald | 137 Studio',
    seoDescription: 'Cruciform by Michael MacDonald — textured abstract painting in deep crimson with a white cross motif. Mixed media on canvas. Contemporary fine art.',
    altText: 'Dark crimson textured abstract painting with combed arcs and a white cross in lower right by Michael MacDonald',
    featured: false,
    order: 4,
  },
  {
    id: 'chaos-garden',
    title: 'Chaos Garden',
    file: '/art/chaos-garden.jpg',
    year: 2024,
    medium: 'Spray paint, acrylic, and stencil on canvas',
    status: 'available',
    description: 'An impossibly dense ecosystem of stenciled flowers, mandala rosettes, hieroglyphic creatures, and gestural scrawl across a dark atmospheric ground. Every square inch rewards closer inspection.',
    longDescription: 'Chaos Garden cultivates an impossibly dense ecosystem of stenciled flowers, mandala rosettes, hieroglyphic creatures, and gestural scrawl across a dark, atmospheric ground. Every square inch rewards closer inspection — cat faces, arrows, numbers, and botanical motifs compete for light like plants on a jungle floor, forming MacDonald\'s most maximalist statement on the beauty of visual overload.',
    tags: ['maximalist', 'floral', 'mandala', 'stencil', 'nocturnal', 'dense', 'botanical'],
    colors: ['#1DA65E', '#3C8EDE', '#D43A5C', '#E8C84A', '#1C1C1C'],
    influences: ['Ryan McGinness', 'Takashi Murakami', 'Barry McGee', 'Keith Haring', 'Islamic patterning'],
    techniques: ['multi-layer stenciling', 'spray paint', 'marker detailing', 'transparent wash overlays', 'pattern-on-pattern density'],
    mood: ['teeming', 'psychedelic', 'nocturnal', 'encyclopedic', 'playful', 'cryptic'],
    seoTitle: 'Chaos Garden | Michael MacDonald | 137 Studio',
    seoDescription: 'Chaos Garden by Michael MacDonald — a dense mixed-media painting of stenciled flowers, mandalas & glyphs in green, blue & pink. Contemporary art.',
    altText: 'Dense mixed-media painting with stenciled flowers, mandalas, and glyphs in green, blue, and pink by Michael MacDonald',
    featured: true,
    order: 5,
  },
  {
    id: 'teal-skull',
    title: 'Teal Skull',
    file: '/art/teal-skull.jpg',
    year: 2024,
    medium: 'Acrylic and marker on canvas',
    status: 'available',
    description: 'A monumental cranium in luminous teal linework against a deep cobalt field, its interior teeming with cryptic symbols and tribal geometry. The unblinking red-centered eye anchors the composition with almost accusatory intensity.',
    longDescription: 'Teal Skull presents a monumental cranium rendered in luminous teal linework against a deep cobalt field, its interior teeming with cryptic symbols and tribal geometry that suggest a mind in constant, restless motion. The unblinking red-centered eye anchors the composition with an almost accusatory intensity, while paint drips at the canvas edge betray the urgency of MacDonald\'s process.',
    tags: ['skull', 'teal', 'portrait', 'tribal', 'geometric', 'street art', 'eye'],
    colors: ['#2ED8C4', '#1A5FB4', '#1C1C1C', '#E8412A', '#FFFFFF'],
    influences: ['Jean-Michel Basquiat', 'KAWS', 'Day of the Dead', 'CoBrA movement', 'Keith Haring'],
    techniques: ['bold continuous linework', 'layered acrylic washes', 'splatter', 'sgraffito', 'impasto'],
    mood: ['electric', 'frenetic', 'hypnotic', 'confrontational', 'cerebral', 'raw'],
    seoTitle: 'Teal Skull | Michael MacDonald | 137 Studio',
    seoDescription: 'Teal Skull by Michael MacDonald — a vivid mixed media skull painting with electric teal linework, street art energy & raw neo-expressionist power.',
    altText: 'Large teal-outlined skull with red eye on deep blue background filled with abstract symbols by Michael MacDonald',
    featured: true,
    order: 6,
  },
  {
    id: 'pink-skull',
    title: 'Pink Skull',
    file: '/art/pink-skull.jpg',
    year: 2024,
    medium: 'Spray paint and acrylic on canvas',
    status: 'available',
    description: 'A skull erupts from a blackened ground in furious loops of neon magenta spray paint, its grinning teeth and hollow eyes emerging and dissolving in a haze of aerosol and gesture. The sky-blue border frames the chaos with street-level defiance.',
    longDescription: 'Pink Skull erupts from a blackened ground in furious loops of neon magenta spray paint, its grinning teeth and hollow eyes emerging and dissolving in a haze of aerosol and gesture. The sky-blue border and gold graffiti tag at lower right frame the chaos with a wink of street-level defiance, bridging gallery wall and alley wall in a single confrontational image.',
    tags: ['skull', 'spray paint', 'magenta', 'graffiti', 'punk', 'neon', 'street art'],
    colors: ['#FF2D9B', '#2A2A2A', '#6DC8E8', '#D8A0D8', '#E8D42A'],
    influences: ['Basquiat', 'Cy Twombly', 'punk zine aesthetics', 'Julian Schnabel', 'SAMO'],
    techniques: ['spray paint aerosol', 'loose gestural brushwork', 'layered overpainting', 'crosshatch', 'drip and splatter', 'graffiti tagging'],
    mood: ['aggressive', 'punk', 'anarchic', 'urgent', 'volatile', 'defiant'],
    seoTitle: 'Pink Skull | Michael MacDonald | 137 Studio',
    seoDescription: 'Pink Skull by Michael MacDonald — neon magenta spray paint skull on black, raw graffiti-inspired mixed media with punk energy and street art edge.',
    altText: 'Hot pink spray-painted skull on black background with blue border and graffiti tag by Michael MacDonald',
    featured: false,
    order: 7,
  },
  {
    id: 'menagerie',
    title: 'Menagerie',
    file: '/art/menagerie.jpg',
    year: 2024,
    medium: 'Mixed media, stencil, and spray paint on canvas',
    status: 'available',
    description: 'A maximalist fever dream in which stenciled mandalas, folkloric creatures, numerical notations, and invented hieroglyphs compete for space across an impossibly layered surface. A visual archaeology where each stratum partially obscures the last.',
    longDescription: 'Menagerie is a maximalist fever dream in which stenciled mandalas, folkloric creatures, numerical notations, and invented hieroglyphs compete for space across an impossibly layered surface. MacDonald builds a visual archaeology — each stratum of pattern and mark partially obscuring the last — creating a work that rewards prolonged looking and refuses any single reading.',
    tags: ['maximalist', 'mandala', 'creatures', 'stencil', 'layered', 'encyclopedic', 'mythic'],
    colors: ['#00A86B', '#3B8FE3', '#D44B7A', '#E8C840', '#1C1C1C'],
    influences: ['Basquiat', 'Takashi Murakami', 'Barry McGee', 'Kenny Scharf', 'outsider art'],
    techniques: ['stencil work', 'multi-layer overpainting', 'marker and paint-pen', 'spray paint', 'scratched notation'],
    mood: ['kaleidoscopic', 'dense', 'mythic', 'cryptic', 'playful', 'obsessive'],
    seoTitle: 'Menagerie | Michael MacDonald | 137 Studio',
    seoDescription: 'Menagerie by Michael MacDonald — dense mixed media painting layering mandalas, creatures & graffiti symbols in a kaleidoscopic neo-expressionist field.',
    altText: 'Densely layered mixed media painting with stenciled flowers, animal figures, numbers, and symbols by Michael MacDonald',
    featured: false,
    order: 8,
  },
  {
    id: 'blue-teeth',
    title: 'Blue Teeth',
    file: '/art/blue-teeth.jpg',
    year: 2024,
    medium: 'Acrylic and marker on canvas',
    status: 'available',
    description: 'A panoramic procession of grinning, grimacing creatures in bold black line over washes of electric blue. The frieze-like composition evokes both ancient narrative scrolls and a punk-rock concert poster.',
    longDescription: 'Blue Teeth unfurls as a panoramic procession of grinning, grimacing creatures rendered in bold black line over washes of electric blue, their oversized teeth gnashing in unison across the wide-format canvas. The frieze-like composition evokes both ancient narrative scrolls and a punk-rock concert poster, balancing menace and dark humor in MacDonald\'s signature vocabulary of eyes, teeth, and raw gesture.',
    tags: ['panoramic', 'skulls', 'teeth', 'frieze', 'blue', 'creatures', 'humor', 'wide format'],
    colors: ['#4AAFE0', '#1A1A1A', '#FFFFFF', '#E03030', '#F0A030'],
    influences: ['Basquiat', 'Philip Guston', 'CoBrA movement', 'Hieronymus Bosch', 'Chicago Imagists'],
    techniques: ['heavy black outline', 'acrylic wash', 'panoramic composition', 'repeated motif', 'drip painting', 'crosshatching'],
    mood: ['carnivalesque', 'manic', 'tribal', 'riotous', 'humorous', 'menacing'],
    seoTitle: 'Blue Teeth | Michael MacDonald | 137 Studio',
    seoDescription: 'Blue Teeth by Michael MacDonald — panoramic mixed media painting of grinning skull creatures in bold blue, black & red with raw street art intensity.',
    altText: 'Wide panoramic painting of multiple grinning blue skull-like creatures with large white teeth by Michael MacDonald',
    featured: false,
    order: 9,
  },
  {
    id: 'orbit',
    title: 'Orbit',
    file: '/art/orbital.jpg',
    year: 2024,
    medium: 'Acrylic on canvas',
    status: 'available',
    description: 'White gestural arcs sweep across a pitch-black field, tracing orbital paths through constellations of splatter. The monochrome palette strips everything to pure kinetic energy \u2014 brush against void, signal against silence.',
    longDescription: 'Orbit reduces MacDonald\'s visual vocabulary to its most elemental: white paint on black ground. Sweeping circular arcs trace planetary paths while bold rectangular brushstrokes anchor the composition like architectural fragments floating in space. The splatter field reads as star dust, and the interplay between controlled geometry and chaotic dispersion suggests the tension between order and entropy that governs all orbital systems.',
    tags: ['monochrome', 'gestural', 'abstract', 'minimal', 'orbital', 'black and white', 'kinetic'],
    colors: ['#1A1A1A', '#E8E4DC', '#808080', '#C0C0C0', '#2A2A2A'],
    influences: ['Franz Kline', 'Robert Motherwell', 'Sumi-e ink painting', 'Abstract Expressionism', 'Pierre Soulages'],
    techniques: ['gestural brushwork', 'splatter', 'palette knife', 'circular arcs', 'monochrome palette'],
    mood: ['cosmic', 'kinetic', 'meditative', 'stark', 'controlled', 'elegant'],
    seoTitle: 'Orbit | Michael MacDonald | 137 Studio',
    seoDescription: 'Orbit by Michael MacDonald \u2014 monochrome abstract painting with sweeping white arcs and splatter on black. Gestural fine art for sale.',
    altText: 'Black and white abstract painting with sweeping white circular arcs and splatter on black ground by Michael MacDonald',
    featured: true,
    order: 10,
  },
  {
    id: 'broken-signal',
    title: 'Broken Signal',
    file: '/art/broken-signal.jpg',
    year: 2024,
    medium: 'Spray paint and stencil on canvas',
    status: 'available',
    description: 'A vintage television rendered in hot pink and orange stencil bleeds through veils of teal and magenta spray, its cracked screen glowing with the ghost of a dead channel. The portal is broken but still transmitting.',
    longDescription: 'Broken Signal captures a vintage CRT television in layers of hot pink, orange, and cyan stencil work, its cracked screen emanating a spectral teal glow. The composition reads as both pop-art homage and technological elegy, the TV as sacred object and obsolete relic simultaneously. MacDonald\'s graffiti tag in the corner claims the signal as his own broadcast.',
    tags: ['television', 'stencil', 'pop art', 'retro', 'portal', 'neon', 'street art', 'CRT'],
    colors: ['#E84080', '#F0A030', '#40E0D0', '#C040C0', '#4AAFE0'],
    influences: ['Andy Warhol', 'Shepard Fairey', 'Nam June Paik', 'pop art', 'street art'],
    techniques: ['multi-layer stenciling', 'spray paint', 'color field layering', 'graffiti tagging'],
    mood: ['nostalgic', 'electric', 'haunted', 'playful', 'luminous'],
    seoTitle: 'Broken Signal | Michael MacDonald | 137 Studio',
    seoDescription: 'Broken Signal by Michael MacDonald \u2014 stenciled vintage TV in hot pink and cyan spray paint with cracked screen. Pop art meets street art.',
    altText: 'Stenciled vintage TV in hot pink, orange, and cyan with cracked glowing screen by Michael MacDonald',
    featured: true,
    order: 11,
  },
  {
    id: 'ultraviolet-beast',
    title: 'Ultraviolet Beast',
    file: '/art/ultraviolet-beast.jpg',
    year: 2024,
    medium: 'UV-reactive acrylic and fluorescent paint on canvas',
    status: 'available',
    description: 'Under blacklight, a continuous-line beast of interlocking faces and spiraling forms emerges from a fluorescent mandala ground. The UV-reactive pigments transform the canvas into a living, breathing organism of purple fire and neon green.',
    longDescription: 'Ultraviolet Beast reveals its true nature only under blacklight. Dense continuous linework traces an interlocking bestiary of faces, eyes, hearts, and spiraling organic forms over a ground of fluorescent mandala patterns and floral stencils. The UV-reactive pigments create an otherworldly luminescence, the painting literally glowing with an energy invisible in daylight. MacDonald\'s most shamanic work, a portal that requires altered conditions to fully perceive.',
    tags: ['UV reactive', 'blacklight', 'fluorescent', 'beast', 'continuous line', 'mandala', 'shamanic', 'psychedelic'],
    colors: ['#9B30FF', '#39FF14', '#FF1493', '#FF6600', '#4B0082'],
    influences: ['Keith Haring', 'Art Nouveau', 'Celtic knotwork', 'blacklight poster art', 'Aboriginal dot painting'],
    techniques: ['continuous line drawing', 'UV-reactive paint', 'fluorescent pigments', 'stenciled ground', 'layered overpainting'],
    mood: ['shamanic', 'psychedelic', 'hypnotic', 'otherworldly', 'teeming', 'nocturnal'],
    seoTitle: 'Ultraviolet Beast | Michael MacDonald | 137 Studio',
    seoDescription: 'Ultraviolet Beast by Michael MacDonald \u2014 UV-reactive blacklight painting of interlocking faces and spirals over fluorescent mandala ground.',
    altText: 'UV blacklight painting of interlocking beast faces in purple continuous line over fluorescent mandala ground by Michael MacDonald',
    featured: true,
    order: 12,
  },
  {
    id: 'the-delegate',
    title: 'The Delegate',
    file: '/art/the-delegate.jpg',
    year: 2024,
    medium: 'Acrylic and ink on canvas',
    status: 'available',
    description: 'A tall, regal figure assembled from interlocking amber and magenta geometric planes stands in formal posture against a pale lavender ground. Part diplomat, part deity, the elongated form carries the authority of something sent to deliver a message.',
    longDescription: 'The Delegate presents a towering cubist figure rendered in hot amber, magenta, and deep black, its elongated neck and fragmented torso suggesting both aristocratic poise and mechanical assembly. The lavender background isolates the figure like a specimen or icon, while the bold continuous-line technique gives the form an urgent, almost calligraphic energy. This is a figure of authority arriving from elsewhere.',
    tags: ['figure', 'portrait', 'cubist', 'tall format', 'amber', 'magenta', 'regal', 'calligraphic'],
    colors: ['#D4A030', '#E84080', '#1A1A1A', '#C87040', '#E8E0F0'],
    influences: ['Amedeo Modigliani', 'Basquiat', 'African sculpture', 'Cubism', 'Oskar Schlemmer'],
    techniques: ['continuous line', 'bold ink outline', 'flat color fill', 'cubist fragmentation', 'elongated proportions'],
    mood: ['regal', 'confrontational', 'urgent', 'authoritative', 'ceremonial'],
    seoTitle: 'The Delegate | Michael MacDonald | 137 Studio',
    seoDescription: 'The Delegate by Michael MacDonald \u2014 tall cubist figure in amber and magenta with bold ink linework. Contemporary neo-expressionist art.',
    altText: 'Tall cubist figure in amber, magenta, and black with elongated neck on lavender background by Michael MacDonald',
    featured: false,
    order: 13,
  },
  {
    id: 'undertow',
    title: 'Undertow',
    file: '/art/undertow.jpg',
    year: 2024,
    medium: 'Acrylic and palette knife on canvas',
    status: 'available',
    description: 'Massive strokes of teal and cerulean impasto crash across the canvas like ocean waves folding over themselves, anchored by a single sweeping black arc. The white border frames the turbulence like a window onto a storm.',
    longDescription: 'Undertow is MacDonald\'s most painterly work, built entirely through heavy palette-knife application of teal, cerulean, and deep ocean blue. The thick, folding strokes create genuine three-dimensional texture, the paint itself becoming the subject. A single bold black arc cuts across the composition like a current pulling everything under. The white border acts as containment, barely holding the energy within the frame.',
    tags: ['abstract', 'impasto', 'oceanic', 'teal', 'palette knife', 'gestural', 'textured', 'blue'],
    colors: ['#2ED8C4', '#1A8CAF', '#2A6090', '#C8D8A0', '#F0F0F0'],
    influences: ['Gerhard Richter', 'Pierre Soulages', 'Helen Frankenthaler', 'de Kooning', 'Zao Wou-Ki'],
    techniques: ['heavy impasto', 'palette knife', 'layered scraping', 'single-line gesture', 'border framing device'],
    mood: ['oceanic', 'turbulent', 'powerful', 'meditative', 'immersive', 'elemental'],
    seoTitle: 'Undertow | Michael MacDonald | 137 Studio',
    seoDescription: 'Undertow by Michael MacDonald \u2014 heavy impasto abstract in teal and cerulean with bold palette knife texture. Contemporary fine art.',
    altText: 'Heavy impasto abstract painting in teal and cerulean blue with black arc on white border by Michael MacDonald',
    featured: true,
    order: 14,
  },
  {
    id: 'rosetta',
    title: 'Rosetta',
    file: '/art/rosetta.jpg',
    year: 2024,
    medium: 'Acrylic and marker on canvas',
    status: 'available',
    description: 'White glyphs, numbers, and sacred symbols swarm across a black field, converging on a blood-red geometric slab where black sigils speak a denser dialect. This is the decoder ring for MacDonald\'s entire visual language.',
    longDescription: 'Rosetta is the key to MacDonald\'s symbolic universe. Hundreds of white hand-painted glyphs \u2014 eyes, spirals, triangles, numbers, crosses, arrows, and invented characters \u2014 populate a black field with the density of an ancient astronomical chart. A blood-red geometric form intrudes from the left, its surface covered in bold black sigils that speak the same language at higher volume. The title is no accident: this is the translation stone between MacDonald\'s private mythology and the viewer\'s perception.',
    tags: ['glyphs', 'symbols', 'cipher', 'numbers', 'sacred geometry', 'red', 'black and white', 'codex', 'language'],
    colors: ['#1A1A1A', '#E8E4DC', '#C41230', '#D4A030', '#808080'],
    influences: ['Basquiat', 'Mark Tobey', 'Cy Twombly', 'cave paintings', 'Proto-Sinaitic script', 'alchemical manuscripts'],
    techniques: ['hand-painted glyphs', 'symbol systems', 'color blocking', 'white on black', 'marker and paint'],
    mood: ['encyclopedic', 'cryptic', 'obsessive', 'sacred', 'archival', 'revelatory'],
    seoTitle: 'Rosetta | Michael MacDonald | 137 Studio',
    seoDescription: 'Rosetta by Michael MacDonald \u2014 white glyphs and sacred symbols on black with red geometric slab. The decoder ring for a visual language.',
    altText: 'Dense white symbols, glyphs, and numbers on black ground with blood-red geometric form by Michael MacDonald',
    featured: true,
    order: 15,
  },
];

// Helper to get featured works
export const featuredWorks = artworks.filter(a => a.featured);

// Helper to get all unique tags
export const allTags = [...new Set(artworks.flatMap(a => a.tags))];

// Helper to get all unique influences
export const allInfluences = [...new Set(artworks.flatMap(a => a.influences))];
