'use client';

// src/app/page.tsx — OWNED BY SCAFFOLD (then INTEGRATION).
// Journey orchestrator: owns the Lenis + ScrollTrigger wiring and the 700vh
// scroll track. Sections are mounted once, in order, and read JourneyContext.
// Section builders: replace your own component files — do NOT edit this file.

import { useEffect } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import {
  JourneyProvider,
  Loader,
  Cursor,
  Grain,
  ScrollProgress,
  Hero,
  Dive,
  Cosmos,
  Contraction,
  Finale,
  WorkModal,
  JOURNEY_HEIGHT_VH,
} from '@/components/journey';
import './journey.css';

gsap.registerPlugin(ScrollTrigger);

export default function JourneyPage() {
  useEffect(() => {
    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const lenis = new Lenis({ lerp: 0.1, smoothWheel: !reduced });
    window.lenis = lenis; // screenshot harness + agents depend on this
    lenis.on('scroll', ScrollTrigger.update);
    const raf = (time: number) => lenis.raf(time * 1000);
    gsap.ticker.add(raf);
    gsap.ticker.lagSmoothing(0);
    const refreshId = requestAnimationFrame(() => ScrollTrigger.refresh());
    return () => {
      cancelAnimationFrame(refreshId);
      gsap.ticker.remove(raf);
      ScrollTrigger.getAll().forEach((t) => t.kill());
      lenis.destroy();
      window.lenis = undefined;
    };
  }, []);

  return (
    <JourneyProvider>
      <div
        className="journey-root"
        style={{
          position: 'relative',
          width: '100%',
          height: `${JOURNEY_HEIGHT_VH}vh`,
          background: '#0e0c0a',
        }}
      >
        <Loader />
        <Cursor />
        <Grain />
        <ScrollProgress />
        <Hero />
        <Dive />
        <Cosmos />
        <Contraction />
        <Finale />
        <WorkModal />
      </div>
    </JourneyProvider>
  );
}
